### ISSUE TITLE
Reason for the number of shift/reduce conflicts

### ISSUE THREAD

**Issue by nachivpn** [silcnitc/silcnitc.github.io#8]
Under section 5.1, it would help to explicitly state the reason for the number of shift/reduce conflicts.

For example: the second ambiguous grammar in section 5.1 causes 4 shift/reduce conflicts.

expr:	expr '+' expr
    |	       expr  '*' expr
    |	       '(' expr ')'
    |	       '0'|'1'|'2'|'3'|'4'|'5'|'6'|'7'|'8'|'9'

This arises due to lack of definitions of precedence (which causes 2 s/r conflicts) and associativity (which causes 2 s/r conflicts). Some explanation of this, would help elucidate the **number** of shift/reduce conflicts. IMO, the current explanation requires an additional step of inference. I faced this myself when trying to revisit these concepts after a while.

**Comment by kmuralinitc** [comment]
The issue has been addressed, Examples added to illustrate the conflicts.
